<a href="https://colab.research.google.com/github/Akanerd/DataScience-Orbit/blob/main/PCA_LDA_Dimentional_Reduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PCA

In [ ]:
import numpy as np #hanya numpy :v

## Step 1

In [ ]:
#dummy dataset
X = np.random.randint(5,50,200).reshape(25,8) 
# mean Centering the data  
X_standrdize = X - np.mean(X , axis = 0)
X_standrdize /= np.std(X_standrdize, axis=0)

## Step 2

In [ ]:
# calculating the covariance matrix of the mean-centered data.
matx_covar = np.cov(X_standrdize , rowvar = False)

## Step 3

In [ ]:
#Calculating Eigenvalues and Eigenvectors of the covariance matrix
eig_vals , eig_vect = np.linalg.eigh(matx_covar)

In [ ]:
eig_vals

array([0.28841921, 0.41572873, 0.80359729, 0.93743431, 1.14717625,
       1.25840679, 1.64099696, 1.84157379])

In [ ]:
eig_vect

array([[ 0.25800473, -0.6617158 ,  0.02901588,  0.21821463, -0.10294737,
         0.09870948,  0.27545781, -0.59235756],
       [-0.51935577, -0.02538685, -0.18855191, -0.08981667,  0.63069739,
        -0.3181118 , -0.05599607, -0.42883139],
       [ 0.00412703, -0.13672678,  0.50952029, -0.58295335, -0.15625467,
        -0.53138552,  0.27232003,  0.0299822 ],
       [-0.32047763,  0.14116485,  0.12602991,  0.6938789 , -0.21439091,
        -0.40882593,  0.39178645,  0.11582913],
       [ 0.20876368,  0.2730956 , -0.58119052, -0.12706128, -0.46475308,
        -0.42999249, -0.11937326, -0.33581333],
       [-0.06297118, -0.65219664, -0.3056599 ,  0.0626722 , -0.01634028,
        -0.33204325, -0.33299955,  0.50190633],
       [-0.54253795, -0.08728898,  0.29261338, -0.00394324, -0.49767944,
         0.16787494, -0.52155671, -0.25398196],
       [ 0.4680653 ,  0.12371316,  0.41385845,  0.32081908,  0.23936666,
        -0.3409162 , -0.54421736, -0.14735483]])

## Step 4

In [ ]:
sort_idx = np.argsort(eig_vals)[::-1] #sort_idx

#sorted eigen values and eigen vectors 
eigenvalue_sorted = eig_vals[sort_idx]
eigenvectors_sorted = eig_vect[:,sort_idx]

In [ ]:
sort_idx

array([7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
eigenvalue_sorted

array([1.84157379, 1.64099696, 1.25840679, 1.14717625, 0.93743431,
       0.80359729, 0.41572873, 0.28841921])

In [ ]:
eigenvectors_sorted

array([[-0.59235756,  0.27545781,  0.09870948, -0.10294737,  0.21821463,
         0.02901588, -0.6617158 ,  0.25800473],
       [-0.42883139, -0.05599607, -0.3181118 ,  0.63069739, -0.08981667,
        -0.18855191, -0.02538685, -0.51935577],
       [ 0.0299822 ,  0.27232003, -0.53138552, -0.15625467, -0.58295335,
         0.50952029, -0.13672678,  0.00412703],
       [ 0.11582913,  0.39178645, -0.40882593, -0.21439091,  0.6938789 ,
         0.12602991,  0.14116485, -0.32047763],
       [-0.33581333, -0.11937326, -0.42999249, -0.46475308, -0.12706128,
        -0.58119052,  0.2730956 ,  0.20876368],
       [ 0.50190633, -0.33299955, -0.33204325, -0.01634028,  0.0626722 ,
        -0.3056599 , -0.65219664, -0.06297118],
       [-0.25398196, -0.52155671,  0.16787494, -0.49767944, -0.00394324,
         0.29261338, -0.08728898, -0.54253795],
       [-0.14735483, -0.54421736, -0.3409162 ,  0.23936666,  0.32081908,
         0.41385845,  0.12371316,  0.4680653 ]])

In [ ]:
n_components = 2 #menentukan n komponen
eigenvector_ncomp = eigenvectors_sorted[:,0:n_components] #pilih eigen vektor berdasarkan jumlah komponennya

In [ ]:
eigenvector_ncomp

array([[-0.59235756,  0.27545781],
       [-0.42883139, -0.05599607],
       [ 0.0299822 ,  0.27232003],
       [ 0.11582913,  0.39178645],
       [-0.33581333, -0.11937326],
       [ 0.50190633, -0.33299955],
       [-0.25398196, -0.52155671],
       [-0.14735483, -0.54421736]])

## Step 5

In [ ]:
#Transform the data 
X_reduced = np.dot(eigenvector_ncomp.transpose(),X_standrdize.transpose()).transpose()


In [ ]:
X_standrdize

array([[ 0.66598476, -1.37860767,  1.04440542, -0.86571726, -0.66205922,
         0.19387875, -0.18003267, -1.16699088],
       [-0.27919012, -0.85903192,  1.28691442,  1.5027545 ,  0.19271207,
         1.61068496,  0.48402226, -0.50013895],
       [-0.4973074 , -0.68584   ,  1.20607808, -1.60076022,  0.81436393,
        -1.29749622,  1.29564496, -1.25034737],
       [-0.06107284,  0.1801196 , -1.2190119 , -0.62070294, -0.73976571,
         1.31240997, -1.06543925,  0.25006947],
       [-0.4973074 , -0.16626424,  0.72106009,  1.66609738,  0.503538  ,
        -0.178965  ,  0.18888674,  0.75020842],
       [ 1.82927692,  2.25842262,  0.47855109,  0.6860401 ,  0.96977689,
        -1.22292747, -0.25381655, -0.9169214 ],
       [-0.93354196, -0.07966828, -0.65315757, -0.1306743 , -1.36141756,
         0.19387875,  1.29564496,  1.9171993 ],
       [ 1.75657116, -0.77243596,  0.15520576,  0.19601146, -1.74994997,
        -1.37206497,  0.85294167,  1.16699088],
       [-0.4973074 ,  0.35331151

In [ ]:
X_reduced

array([[ 0.6650515 ,  0.9493481 ],
       [ 1.44087017,  0.37078592],
       [-0.63008184, -0.05773902],
       [ 0.99137534, -0.53118218],
       [ 0.16304561,  0.21413112],
       [-2.69813849,  1.69937922],
       [ 0.495348  , -2.10292476],
       [-1.17150129,  0.232015  ],
       [ 0.21220313, -0.74590024],
       [ 1.55198086, -1.721129  ],
       [ 0.72175854,  0.43790029],
       [ 1.39038986,  0.45045727],
       [ 0.57369579,  2.11972424],
       [-0.62887251,  1.69046012],
       [ 1.79913323,  1.96210596],
       [-1.29406775,  0.23985298],
       [-2.91773066, -1.41475506],
       [-0.97812395,  0.2799163 ],
       [-1.8471031 , -0.58598118],
       [ 1.11383505,  1.35794973],
       [ 1.03586859,  0.17999627],
       [ 0.65462438, -1.15950857],
       [ 0.90951896, -0.82090389],
       [ 0.48326634, -3.02653263],
       [-2.03634577, -0.017466  ]])

# End to end PCA